# Generated by Django 2.1.3 on 2018-11-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_inventory', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesList',
            fields=[
                ('buy_date', models.DateTimeField(auto_created=True)),
                ('serial_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_num', models.IntegerField()),
                ('total_money', models.FloatField()),
                ('receive_money', models.FloatField()),
                ('return_money', models.FloatField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductCategory'),
        ),
    ]
