# Generated by Django 2.1.3 on 2018-11-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_id', models.CharField(max_length=100)),
                ('produce_name', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('produce_num', models.IntegerField()),
                ('total_money', models.FloatField()),
                ('serial_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SalesList')),
            ],
        ),
    ]
