# Generated by Django 2.1.3 on 2018-11-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_saleslistdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslistdetail',
            old_name='produce_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='saleslistdetail',
            old_name='produce_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='saleslistdetail',
            old_name='produce_num',
            new_name='product_num',
        ),
    ]
