# Generated by Django 2.1.3 on 2018-11-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceURL',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100)),
                ('province_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('province_name', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
    ]
